# Generated by Django 3.2.1 on 2022-04-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0002_rename_neighbourhood_business_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
