# Generated by Django 3.2.1 on 2022-04-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodwatch', '0003_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='title',
        ),
    ]
